version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: davidraffelt/docker-airflow:1.8.1
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        # volumes:
            # - ~/dev/docker-airflow/dags:/usr/local/airflow/dags
            # - ~/dev/docker-airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
